### ISSUE TITLE
Milestone 1: Explore the model

### ISSUE THREAD

**Issue by Jelledb** [cloudfoundation-community/cloudfoundation.org#54]
Goal: create a digital overview that looks like the following: 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/14248574/154441114-78078425-2cee-4c6d-9dd9-8ee26668a6fd.png">

Reno will send over the assets & color codes for the website.

When clicking on 'Maturity Model' on the current website, that is where the new overview should be placed.

All the data of the blocks are already present on the Vuepress website. There is no need to do any backend work. 

Sub-tasks:
- [ ] Render the overview on a separate page
- [ ] Link the 'Maturity Model' menu item at the top to the new page.
- [ ] To make it mobile-friendly (needs collaboration with Reno)
